language: cpp

compiler:
  - gcc
  - clang
  
sudo: required

before_install:
    - sudo apt-get install libsdl2-2.0-0
    - wget https://www.libsdl.org/release/SDL2-2.0.7.tar.gz -O SDL2-2.0.7.tar.gz
    - tar -xzvf SDL2-2.0.7.tar.gz
    # C++14
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - "(cd SDL2-2.0.7 && ./configure && make && sudo make install)"
    # C++14
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    
script:
#task 1 HelloWorld
  - cd 01_HelloWorld
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./hello

 #task 2 SDL Dynamic
  - cd ../../02_SDL_Dynamic
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./SDL-Dynamic
  
#task 2 SDL Static
  - cd ../../02_SDL_Static
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./SDL-Static
  
#task 3 SDL Init
  - cd ../../03_SDL_Init
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  
#task 3 Micro Engine DLL
  - cd ../../03_MicroEngine
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - sudo cp libengine.so /usr/local/lib
  - sudo cp libengine.so /lib
  - sudo cp libengine.so /usr/lib
  - sudo cp libengine.so ../../03_Game
  
#task 3 Game
  - cd ../../03_Game
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - sudo cp game ./../
  - cd ..
  - sudo ls -la
  - ./game
