language: cpp

compiler:
  - gcc
  - clang
  
sudo: required

install: 
    - sudo apt-get update
    - sudo apt-get install build-essential mercurial make cmake autoconf automake libtool libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libgl1-mesa-dev libesd0-dev libdbus-1-dev libudev-dev libgles1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev libsndio-dev
    - sudo apt-get install libsdl2-dev
    
script:
#task 1 HelloWorld
  - cd 01_HelloWorld
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./hello

 #task 2 SDL Dynamic
  - cd ../../02_SDL_Dynamic
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./SDL-Dynamic
  
#task 2 SDL Static
  - cd ../../02_SDL_Static
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./SDL-Static
  
#task 3 SDL Init
  - cd ../../03_SDL_Init
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./SDL-Init
  
#task 3 Micro Engine DLL
  - cd ../../03_MicroEngine
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - cp libengine.so /usr/local/lib/libengine.so
  
#task 3 SDL Init
  - cd ../../03_Game
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./game ../config.json
