language: cpp

compiler:
  - gcc
  - clang
  
sudo: required

before_install:
    - wget https://www.libsdl.org/release/SDL2-2.0.5.tar.gz -O SDL2-2.0.5.tar.gz
    - tar -xzvf SDL2-2.0.7.tar.gz

install:
    - "(cd SDL2-2.0.7 && ./configure && make && sudo make install)"
  
  
script:
#task 1 HelloWorld
  - cd 1_HelloWorld
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./hello

 #task 2 SDL Dynamic
  - cd ../../2_SDL_Dynamic
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./SDL-Dynamic
  
#task 2 SDL Static
  - cd ../../2_SDL_Static
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./SDL-Static