language: cpp

compiler:
  - gcc
  - clang

script:
#task 1 HelloWorld
  - cd 1_HelloWorld
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./hello

 #task 2 SDL Dynamic
  - cd ../../2_SDL_Dynamic
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./SDL-Dynamic
  
#task 2 SDL Static
  - cd ../../2_SDL_Static
  - 'if [ ! -d "./build" ];
        then mkdir build;
     fi'
  - cd build
  - cmake ..
  - make
  - ./SDL-Static